### ISSUE TITLE
Broken pipe on continues tests

### ISSUE THREAD

**Issue by kaiokenx10** [thoughtbot/capybara-webkit#1012]
Hi,

I'm having the following issue with the capybara webkit:
```
Failure/Error: visit "/logout"#logout_path
     
     Capybara::Webkit::CrashError:
       The webkit_server process crashed!
     
         Broken pipe
     
       This is a bug in capybara-webkit. For help with this crash, please visit:
     
       https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
     # /bundler_box/gems/capybara-webkit-1.14.0/lib/capybara/webkit/browser.rb:227:in `rescue in command'
     # /bundler_box/gems/capybara-webkit-1.14.0/lib/capybara/webkit/browser.rb:215:in `command'
     # /bundler_box/gems/capybara-webkit-1.14.0/lib/capybara/webkit/browser.rb:20:in `visit'
     # /bundler_box/gems/capybara-webkit-1.14.0/lib/capybara/webkit/driver.rb:50:in `visit'
     # /bundler_box/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /bundler_box/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/support/session_helper.rb:17:in `logout_user'
     # ./spec/support/session_helper.rb:7:in `login_user'
     # ./spec/features/change_password_spec.rb:9:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:86:in `block (3 levels) in <top (required)>'
     # ./spec/support/background_jobs.rb:5:in `run_background_jobs_immediately'
     # ./spec/rails_helper.rb:85:in `block (2 levels) in <top (required)>'
     # ./spec/support/headless.rb:4:in `block (3 levels) in <top (required)>'
     # /bundler_box/gems/headless-2.3.1/lib/headless.rb:143:in `run'
     # ./spec/support/headless.rb:3:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::EPIPE:
     #   Broken pipe
     #   /bundler_box/gems/capybara-webkit-1.14.0/lib/capybara/webkit/connection.rb:22:in `write'
```

I have the docker setup made based on the [thoughtbot tutorial](https://robots.thoughtbot.com/rails-on-docker#developing-with-docker-docker-compose-and-rails):
- capybara 2.4.4
- capybara-webkit 1.14.0
- default Qt for debian which is 5.3.2

here is the Dockerfile:
```
FROM ruby:2.4.0-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential git libpq-dev libxml2-dev libxslt1-dev cron imagemagick nodejs \
                          xvfb qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x && \
    mkdir -p /app

RUN touch /var/log/cron.log

WORKDIR /app

COPY Gemfile Gemfile.lock ./

ENV BUNDLE_PATH /bundler_box

COPY . ./

CMD ["docker/entrypoint.sh"]
```

Single tests go fine but when I run the whole test suit it fails (1 ends up with success and the next one fails) with the error posted at the beginning. It starts when in my `before` block I visit the logout path in order to login in with the user once again to achieve the total isolation for each scenario.

Here is the debug log:
```
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(fonts.googleapis.com)"
Started "AllowUrl(fonts.googleapis.com)"
Finished "AllowUrl(fonts.googleapis.com)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "AllowUrl(lvh.me)"
Started "AllowUrl(lvh.me)"
Finished "AllowUrl(lvh.me)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Visit(http://127.0.0.1:33333/logout)"
Started "Visit(http://127.0.0.1:33333/logout)"
Load started
"Visit(http://127.0.0.1:33333/logout)" started page load
Started request to "http://127.0.0.1:33333/logout"
Finished "Visit(http://127.0.0.1:33333/logout)" with response "Success()"
Started request to "http://127.0.0.1:33333/"
Received 302 from "http://127.0.0.1:33333/logout"
Started request to "http://127.0.0.1:33333/assets/application-819babdfa9bc1e541fc9bab5887b063c48f82621e308568547f1214e5dd47c8c.css"
Started request to "http://127.0.0.1:33333/assets/application-565c8364d3e90026cb1dbecd86f7df3da96f0560b4b2af98fa2081214cd90f51.js"
Started request to "https://fonts.googleapis.com/css?family=Roboto:400,500"
Received 200 from "http://127.0.0.1:33333/"
Received 200 from "http://127.0.0.1:33333/assets/application-819babdfa9bc1e541fc9bab5887b063c48f82621e308568547f1214e5dd47c8c.css"
Started request to "https://fonts.googleapis.com/css?family=Anton"
Started request to "https://fonts.googleapis.com/css?family=Roboto"
Received 200 from "http://127.0.0.1:33333/assets/application-565c8364d3e90026cb1dbecd86f7df3da96f0560b4b2af98fa2081214cd90f51.js"
Received 200 from "https://fonts.googleapis.com/css?family=Roboto:400,500"
Received 200 from "https://fonts.googleapis.com/css?family=Anton"
Received 200 from "https://fonts.googleapis.com/css?family=Roboto"
Page finished with true
Load finished
Page load from command finished
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Visit(http://127.0.0.1:33333/login)"
Started "Visit(http://127.0.0.1:33333/login)"
Load started
"Visit(http://127.0.0.1:33333/login)" started page load
Started request to "http://127.0.0.1:33333/login"
Finished "Visit(http://127.0.0.1:33333/login)" with response "Success()"
Received 200 from "http://127.0.0.1:33333/login"
Page finished with true
Load finished
Page load from command finished
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindXpath(.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))][((((./@id = 'Email') or (./@name = 'Email')) or (./@placeholder = 'Email')) or (./@id = //label[(normalize-space(string(.)) = 'Email')]/@for))] | .//label[(normalize-space(string(.)) = 'Email')]//.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))])"
Started "FindXpath(.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))][((((./@id = 'Email') or (./@name = 'Email')) or (./@placeholder = 'Email')) or (./@id = //label[(normalize-space(string(.)) = 'Email')]/@for))] | .//label[(normalize-space(string(.)) = 'Email')]//.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))])"
Finished "FindXpath(.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))][((((./@id = 'Email') or (./@name = 'Email')) or (./@placeholder = 'Email')) or (./@id = //label[(normalize-space(string(.)) = 'Email')]/@for))] | .//label[(normalize-space(string(.)) = 'Email')]//.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))])" with response "Success(1)"
Wrote response true "1"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.set"
Started "Node.set"
Finished "Node.set" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindXpath(.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))][((((./@id = 'Password') or (./@name = 'Password')) or (./@placeholder = 'Password')) or (./@id = //label[(normalize-space(string(.)) = 'Password')]/@for))] | .//label[(normalize-space(string(.)) = 'Password')]//.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))])"
Started "FindXpath(.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))][((((./@id = 'Password') or (./@name = 'Password')) or (./@placeholder = 'Password')) or (./@id = //label[(normalize-space(string(.)) = 'Password')]/@for))] | .//label[(normalize-space(string(.)) = 'Password')]//.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))])"
Finished "FindXpath(.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))][((((./@id = 'Password') or (./@name = 'Password')) or (./@placeholder = 'Password')) or (./@id = //label[(normalize-space(string(.)) = 'Password')]/@for))] | .//label[(normalize-space(string(.)) = 'Password')]//.//*[self::input | self::textarea][not(((((((./@type = 'submit') or (./@type = 'image')) or (./@type = 'radio')) or (./@type = 'checkbox')) or (./@type = 'hidden')) or (./@type = 'file')))])" with response "Success(2)"
Wrote response true "2"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.set"
Started "Node.set"
Finished "Node.set" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindXpath(.//input[((((./@type = 'submit') or (./@type = 'reset')) or (./@type = 'image')) or (./@type = 'button'))][(((./@id = 'Log in') or (./@value = 'Log in')) or (./@title = 'Log in'))] | .//input[(./@type = 'image')][(./@alt = 'Log in')] | .//button[((((./@id = 'Log in') or (./@value = 'Log in')) or (normalize-space(string(.)) = 'Log in')) or (./@title = 'Log in'))] | .//input[(./@type = 'image')][(./@alt = 'Log in')])"
Started "FindXpath(.//input[((((./@type = 'submit') or (./@type = 'reset')) or (./@type = 'image')) or (./@type = 'button'))][(((./@id = 'Log in') or (./@value = 'Log in')) or (./@title = 'Log in'))] | .//input[(./@type = 'image')][(./@alt = 'Log in')] | .//button[((((./@id = 'Log in') or (./@value = 'Log in')) or (normalize-space(string(.)) = 'Log in')) or (./@title = 'Log in'))] | .//input[(./@type = 'image')][(./@alt = 'Log in')])"
Finished "FindXpath(.//input[((((./@type = 'submit') or (./@type = 'reset')) or (./@type = 'image')) or (./@type = 'button'))][(((./@id = 'Log in') or (./@value = 'Log in')) or (./@title = 'Log in'))] | .//input[(./@type = 'image')][(./@alt = 'Log in')] | .//button[((((./@id = 'Log in') or (./@value = 'Log in')) or (normalize-space(string(.)) = 'Log in')) or (./@title = 'Log in'))] | .//input[(./@type = 'image')][(./@alt = 'Log in')])" with response "Success(3)"
Wrote response true "3"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.leftClick"
Started "Node.leftClick"
Finished "Node.leftClick" with response "Success()"
Wrote response true ""
Load started
Started request to "http://127.0.0.1:33333/login"
Received "ConsoleMessages()"
"TimeoutCommand" waiting for load to finish
Started request to "http://127.0.0.1:33333/clients"
Received 302 from "http://127.0.0.1:33333/login"
Received 200 from "http://127.0.0.1:33333/clients"
Started request to "http://127.0.0.1:33333/assets/icon_clients-93aa866da420d06f01efd636f4801ed337bba14211fda413b32835e6cdfbb49f.png"
Received 200 from "http://127.0.0.1:33333/assets/icon_clients-93aa866da420d06f01efd636f4801ed337bba14211fda413b32835e6cdfbb49f.png"
Page finished with true
Load finished
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(#avatar-menu)"
Started "FindCss(#avatar-menu)"
Finished "FindCss(#avatar-menu)" with response "Success(1)"
Wrote response true "1"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.leftClick"
Started "Node.leftClick"
Finished "Node.leftClick" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindXpath(.//a[./@href][((((./@id = 'Profile') or (normalize-space(string(.)) = 'Profile')) or (./@title = 'Profile')) or .//img[(./@alt = 'Profile')])])"
Started "FindXpath(.//a[./@href][((((./@id = 'Profile') or (normalize-space(string(.)) = 'Profile')) or (./@title = 'Profile')) or .//img[(./@alt = 'Profile')])])"
Finished "FindXpath(.//a[./@href][((((./@id = 'Profile') or (normalize-space(string(.)) = 'Profile')) or (./@title = 'Profile')) or .//img[(./@alt = 'Profile')])])" with response "Success(2)"
Wrote response true "2"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.leftClick"
Started "Node.leftClick"
Load started
"Node.leftClick" started page load
Started request to "http://127.0.0.1:33333/users/190/edit"
Finished "Node.leftClick" with response "Success()"
Received 200 from "http://127.0.0.1:33333/users/190/edit"
Page finished with true
Load finished
Page load from command finished
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(a[data-target='#change_password_modal190'])"
Started "FindCss(a[data-target='#change_password_modal190'])"
Finished "FindCss(a[data-target='#change_password_modal190'])" with response "Success(1)"
Wrote response true "1"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.leftClick"
Started "Node.leftClick"
Finished "Node.leftClick" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(#change_password_modal190)"
Started "FindCss(#change_password_modal190)"
Finished "FindCss(#change_password_modal190)" with response "Success(2)"
Wrote response true "2"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(#change_password_modal190)"
Started "FindCss(#change_password_modal190)"
Finished "FindCss(#change_password_modal190)" with response "Success(3)"
Wrote response true "3"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(#change_password_modal190)"
Started "FindCss(#change_password_modal190)"
Finished "FindCss(#change_password_modal190)" with response "Success(4)"
Wrote response true "4"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(#change_password_modal190)"
Started "FindCss(#change_password_modal190)"
Finished "FindCss(#change_password_modal190)" with response "Success(5)"
Wrote response true "5"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindCss(#change_password_modal190)"
Started "FindCss(#change_password_modal190)"
Finished "FindCss(#change_password_modal190)" with response "Success(6)"
Wrote response true "6"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.text"
Started "Node.text"
Finished "Node.text" with response "Success(?
Change Password
CURRENT PASSWORDNEW PASSWORDCONFIRM PASSWORD
Close  
)"
Wrote response true "?
Change Password
CURRENT PASSWORDNEW PASSWORDCONFIRM PASSWORD
Close  
"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success(7)"
Wrote response true "7"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.set"
Started "Node.set"
Finished "Node.set" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success(8)"
Wrote response true "8"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.set"
Started "Node.set"
Finished "Node.set" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success(9)"
Wrote response true "9"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.set"
Started "Node.set"
Finished "Node.set" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success(10)"
Wrote response true "10"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.leftClick"
Started "Node.leftClick"
Started request to "http://127.0.0.1:33333/change_password"
Finished "Node.leftClick" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received 422 from "http://127.0.0.1:33333/change_password"
Received "FindXpath(/html)"
Started "FindXpath(/html)"
Finished "FindXpath(/html)" with response "Success(11)"
Wrote response true "11"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Node.text"
Started "Node.text"
Finished "Node.text" with response "Success(timenotes U
MANAGE
 Projects
 Team
 Clients
My Profile

CREDENTIALS
MY NAMEMY EMAILMY PASSWORD
Change Password

 
?
Change Password
New Password must be different than previous one.
CURRENT PASSWORDNEW PASSWORDCONFIRM PASSWORD
Close  
)"
Wrote response true "timenotes U
MANAGE
 Projects
 Team
 Clients
My Profile

CREDENTIALS
MY NAMEMY EMAILMY PASSWORD
Change Password

 
?
Change Password
New Password must be different than previous one.
CURRENT PASSWORDNEW PASSWORDCONFIRM PASSWORD
Close  
"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "CurrentUrl()"
Started "CurrentUrl()"
Finished "CurrentUrl()" with response "Success(http://127.0.0.1:33333/users/190/edit)"
Wrote response true "http://127.0.0.1:33333/users/190/edit"
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Reset()"
Started "Reset()"
Finished "Reset()" with response "Success()"
Wrote response true ""
Received "EnableLogging()"
Started "EnableLogging()"
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(fonts.googleapis.com)"
Started "AllowUrl(fonts.googleapis.com)"
Finished "AllowUrl(fonts.googleapis.com)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "AllowUrl(lvh.me)"
Started "AllowUrl(lvh.me)"
Finished "AllowUrl(lvh.me)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
.Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(fonts.googleapis.com)"
Started "AllowUrl(fonts.googleapis.com)"
Finished "AllowUrl(fonts.googleapis.com)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "AllowUrl(lvh.me)"
Started "AllowUrl(lvh.me)"
Finished "AllowUrl(lvh.me)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
```

**Comment by twalpole** [comment]
First, Capybara 2.4.4 is ancient, upgrade to whatever the latest version of Capybara supported by capybara-webkit is and try again.  Second, I'm unclear as to why you're visiting the logout page first on every test.  The logging out of the user should be covered by the browser and DB resets that should be occurring between each test.

**Comment by twalpole** [comment]
Closing due to lack of response.
