### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for

### ISSUE THREAD

**Issue by Ph0ny** [thoughtbot/capybara-webkit#1017]
Heads up:

`rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFaeRoles < ActiveRecord::Migration[4.2]
/vagrant/db/migrate/20170712130807_create_fae_roles.fae.rb:2:in `<top (required)>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFaeRoles < ActiveRecord::Migration[4.2]
/vagrant/db/migrate/20170712130807_create_fae_roles.fae.rb:2:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
        rake  fae:seed_db
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: fae_roles: DELETE FROM "fae_roles"
/vagrant/lib/tasks/fae_tasks.rake:4:in `block (2 levels) in <top (required)>'
SQLite3::SQLException: no such table: fae_roles
/vagrant/lib/tasks/fae_tasks.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => fae:seed_db
(See full trace by running task with --trace)`

Adding class CreateFaeRoles < ActiveRecord::Migration[5.1] or similar solved this. Dont know if it's a global issue tho.

**Comment by Ph0ny** [comment]
Ah, sorry. Wrong repo. :)
