### ISSUE TITLE
EOFError: end of file reached on qt 5.9?

### ISSUE THREAD

**Issue by faelsoto** [thoughtbot/capybara-webkit#1066]
Hello. I'm having some issues with a few tests. The weird thing is that on my other development machine, everything's working smoothly.

Here's the version output.

```
Capybara: 2.13.0
capybara-webkit: 1.15.0
Qt: 5.9.1
WebKit: 538.1
QtWebKit: 5.9.1
```

What's interesting is that on my laptop, the one that runs without issues, both Qt and QtWebkit are at 5.5.1.

Here's the output:

```
  1) Error:
Onboarding2018Test#test_registro:_layout_test:
EOFError: end of file reached
    test/integration/onboarding_2018_test.rb:17:in `block (2 levels) in <class:Onboarding2018Test>'
    test/integration/onboarding_2018_test.rb:16:in `block in <class:Onboarding2018Test>'

Error:
Onboarding2018Test#test_registro:_layout_test:
Capybara::Webkit::CrashError: The webkit_server process crashed!

  Broken pipe

This is a bug in capybara-webkit. For help with this crash, please visit:

https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
    test/test_helper.rb:77:in `teardown'
```

And here's the [debug output](https://gist.github.com/faelsoto/e5b1bd21d9dd345fbed8275aa68c9a96).

**Comment by mfittko** [comment]
getting the same errors, when installing the qt packages as suggested [here](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#debian--ubuntu) on debian stretch :(

**Comment by keysen** [comment]
Same thing with qt 5.9.5 and capybara 2.18.0  on ubuntu 18.04

**Comment by kiawizard** [comment]
The same for QT 5.9.2 and Capybara 2.18.0 on CentOS 7
