### ISSUE TITLE
Receiving a Capybara::Driver::Webkit::NodeNotAttachedError

### ISSUE THREAD

**Issue by rb2k** [thoughtbot/capybara-webkit#319]
I receive this errors in the following workflow:
1. I click a link, this triggers a "tab" to open via AJAX and display "Loading..."
2. I wait for this "loading" message to disappear using
   
   wait_until(30){ page.has_no_css?('div.field-settings-message', :visible => true) }
3. I wait for the actual content to be present using  
   
   wait_until(30){ page.has_css?("div.form-builder-field-configure div.form-item-title input#edit-title", :visible => true) }

I receive the exception in the call in step number 2

Any idea what could cause this?

The stack trace that cucumber is giving me isn't all that helpful:

```
Capybara::Driver::Webkit::NodeNotAttachedError (Capybara::Driver::Webkit::NodeNotAttachedError)
  (eval):2:in `send'
  (eval):2:in `has_no_css?'
```

Any idea what could cause this?  
Seems like the element disappears somewhere within the has_css? call which capybara-webkit didn't expect

capybara-webkit 0.11  
ruby 1.8.7  
Qt-4.7.4

**Comment by andreychernih** [comment]
I am experiencing the same problem and looks like it's related to page reloading:

```
page.click_on 'Download'
expect(page).not_to have_content 'Download' # raises Capybara::Webkit::NodeNotAttachedError in Travis sometimes
```

Reference: https://travis-ci.org/andreychernih/railsbox/builds/57341072

**Comment by andreychernih** [comment]
Full backtrace:

```
     Failure/Error: expect(page).not_to have_content 'Download'
     Capybara::Webkit::NodeNotAttachedError:
       Element at 2 no longer present in the DOM
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.3.1/lib/capybara/webkit/browser.rb:275:in `check'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.3.1/lib/capybara/webkit/browser.rb:208:in `command'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.3.1/lib/capybara/webkit/node.rb:129:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.3.1/lib/capybara/webkit/node.rb:83:in `visible?'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/element.rb:176:in `block in visible?'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/element.rb:176:in `visible?'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/query.rb:47:in `matches_filters?'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/result.rb:27:in `block in initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/result.rb:27:in `select'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/result.rb:27:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/query.rb:118:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/query.rb:118:in `block in resolve_for'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/query.rb:106:in `resolve_for'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:32:in `block in find'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/document.rb:23:in `text'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/queries/text_query.rb:26:in `resolve_for'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:474:in `block in assert_no_text'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:473:in `assert_no_text'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
     # ./vendor/bundle/ruby/2.2.0/gems/capybara-2.4.4/lib/capybara/rspec/matchers.rb:71:in `does_not_match?'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/handler.rb:75:in `does_not_match?'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/handler.rb:70:in `handle_matcher'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-expectations-3.1.2/lib/rspec/expectations/expectation_target.rb:67:in `not_to'
     # ./spec/features/virtual_boxes_spec.rb:3:in `wait_for_download'
     # ./spec/features/virtual_boxes_spec.rb:19:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `block in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-rails-3.1.0/lib/rspec/rails/adapters.rb:72:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:380:in `execute_with'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:446:in `block (2 levels) in run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:447:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:331:in `with_around_example_hooks'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `block in run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block (2 levels) in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `map'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
     # ./vendor/bundle/ruby/2.2.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
     # ./vendor/bundle/ruby/2.2.0/bin/rspec:23:in `load'
     # ./vendor/bundle/ruby/2.2.0/bin/rspec:23:in `<main>'
```

**Comment by toothrot** [comment]
@andreychernih Page loading makes sense. After diving into this way deeper (we were deeply plagued by this issue), I noticed that this was directly related to selecting elements with the same selector on two different pages. The best thing you can do is try to wait for the new page load, or do a positive assertion for an element that only exists on the new page.

If clicking on 'download' causes a page reload, in your example, then you're going to have to follow that up with a positive assertion (assert that something is actually there on the *new* page). Otherwise, there is a slight race condition. This is good anyway, since you should likely be giving the user some kind of feedback.

Capybara webkit tries to handle this wait condition by pausing selectors for the new page load to happen, but there is definitely a tiny race condition there still, depending on your environment.

In my experience, capybara-webkit works best if you always ensure that you're on the page you're think you are by selecting something that should be there after a particular action.

**Comment by andreychernih** [comment]
Thanks for explanation, @toothrot 

I actually was not able to check for a presence of some element - I am testing binary file download function and I don't have HTML structure. What seems to be working for me is replacing `have_content` matcher with this hack:

```ruby
page.document.synchronize(2) do
  raise Capybara::ElementNotFound unless page.response_headers['Content-Type'] =~ /zip/
end
```

I think there's a problem with `have_content` matcher - although it uses `synchronize`, it does not raises `Capybara::ElementNotFound` which is caught by `synchronize`.

**Comment by arrtchiu** [comment]
Sometimes my CI provider is slow and I see this still. Using Capybara 2.4.4, Capybara-Webkit 1.11.1.

```ruby
it 'redirects when the database changes' do
  visit wait_for_changes_path

  # this page polls and navigates to a new page when the database changes
  expect(page).to have_text 'this page reloads itself'

  make_database_change

  expect(page).to have_text 'this is the destination page'
end
```

It seems this works if I use another matcher than `have_text` -> Switching to `expect(page).to have_link 'this link is only on destination page'` seems to fix the issue. Some kind of cache getting in the way here, perhaps?

**Comment by twalpole** [comment]
@arrtchiu What error exactly are you getting? Also Capybara 2.4.4 is 2 years old -- there have been many updates/fixes for issues since then - you should probably update to something newer if at all possible.
