### ISSUE TITLE
Cucumber hangs in the same place whilst starting request to external script resource?

### ISSUE THREAD

**Issue by richhollis** [thoughtbot/capybara-webkit#551]
Whilst running my cucumber tests this morning cucumber stopped and hung in the same place every time I ran the tests. Running the script on its own didn't hang - it was only when running the entire suite that it would hang. It didn't seem to timeout either and return to the console, it just sat there until I broke it. 

When breaking on the hanging feature test I got this:

```
Exiting... Interrupt again to exit immediately.
    Then I see "Get a Room" page                                                     # features/step_definitions/page_steps.rb:90
      No response received from the server. (Capybara::Webkit::NoResponseError)
      ./features/step_definitions/page_steps.rb:91:in `/^I see "(.*?)" page$/'
      features/manage_users.feature:96:in `Then I see "Get a Room" page'
      Broken pipe (Errno::EPIPE)
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-webkit-1.0.0/lib/capybara/webkit/connection.rb:28:in `write'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-webkit-1.0.0/lib/capybara/webkit/connection.rb:28:in `puts'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-webkit-1.0.0/lib/capybara/webkit/connection.rb:28:in `puts'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-webkit-1.0.0/lib/capybara/webkit/browser.rb:146:in `command'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-webkit-1.0.0/lib/capybara/webkit/browser.rb:38:in `reset!'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-webkit-1.0.0/lib/capybara/webkit/driver.rb:155:in `reset!'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-2.1.0/lib/capybara/session.rb:77:in `reset!'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-2.1.0/lib/capybara.rb:245:in `block in reset_sessions!'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-2.1.0/lib/capybara.rb:245:in `each'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-2.1.0/lib/capybara.rb:245:in `reset_sessions!'
      /home/rich/.rvm/gems/ruby-2.0.0-p0/gems/capybara-2.1.0/lib/capybara/cucumber.rb:10:in `After'
```

When running with debug enabled I saw this at the end of the log:

```
Load started 
Started request to "http://127.0.0.1:47764/logout" 
Started request to "http://127.0.0.1:47764/" 
Received 302 from "http://127.0.0.1:47764/logout" 
Started request to "http://127.0.0.1:47764/assets/application.css" 
Started request to "http://127.0.0.1:47764/assets/application.js" 
Received 200 from "http://127.0.0.1:47764/" 
Received 304 from "http://127.0.0.1:47764/assets/application.css" 
Received 304 from "http://127.0.0.1:47764/assets/application.js" 
Started request to "http://jesseddy.wufoo.com/embed/z7x2x3/def/embedKey=z7x2x3679397&referrer=http%3Awuslashwuslash127.0.0.1%3A47764wuslashcalendar%3F_setdate%3D2013-07-01%252000%3A00%3A00" 
undefined|0|TypeError: 'undefined' is not a function 
Received "Reset" 
"TimeoutCommand" waiting for load to finish 
```

After I removed the external (wufoo) script in the page that was supposed to be rendering at the time, everything runs through fine - which is an ok workaround for me. The external script appears to be fine when requested in a browser so I don't think that it's the problem. It seems to be getting stuck whilst requesting that external script.

Gems included by the bundle:
```
  * actionmailer (3.2.13)
  * actionpack (3.2.13)
  * activemodel (3.2.13)
  * activerecord (3.2.13)
  * activeresource (3.2.13)
  * activesupport (3.2.13)
  * arel (3.0.2)
  * backbone-on-rails (1.0.0.0)
  * bcrypt-ruby (3.0.1)
  * be_valid_asset (1.2.3)
  * builder (3.0.4)
  * bundler (1.3.4)
  * callsite (0.0.11)
  * capistrano (2.14.2)
  * capybara (2.1.0)
  * capybara-webkit (1.0.0)
  * coffee-rails (3.2.2)
  * coffee-script (2.2.0)
  * coffee-script-source (1.6.2)
  * commonjs (0.2.6)
  * cucumber (1.3.5)
  * cucumber-rails (1.3.1)
  * database_cleaner (0.9.1)
  * devise (2.2.3)
  * diff-lcs (1.2.4)
  * eco (1.0.0)
  * eco-source (1.1.0.rc.1)
  * ejs (1.1.1)
  * erubis (2.7.0)
  * execjs (1.4.0)
  * factory_girl (4.1.0)
  * factory_girl_rails (4.1.0)
  * faker (1.1.2)
  * gherkin (2.12.0)
  * haml (4.0.2)
  * haml-rails (0.4)
  * headless (1.0.1)
  * highline (1.6.16)
  * hike (1.2.3)
  * i18n (0.6.1)
  * jasminerice (0.0.10)
  * journey (1.0.4)
  * jquery-rails (2.2.1)
  * json (1.8.0)
  * less (2.3.2)
  * less-rails (2.3.3)
  * libv8 (3.11.8.17)
  * mail (2.5.4)
  * meta_request (0.2.6)
  * mime-types (1.23)
  * mini_portile (0.5.1)
  * multi_json (1.7.7)
  * multi_test (0.0.2)
  * mysql2 (0.3.11)
  * net-scp (1.1.0)
  * net-sftp (2.1.1)
  * net-ssh (2.6.6)
  * net-ssh-gateway (1.2.0)
  * nokogiri (1.6.0)
  * orm_adapter (0.4.0)
  * polyglot (0.3.3)
  * rabl (0.8.5)
  * rack (1.4.5)
  * rack-cache (1.2)
  * rack-contrib (1.1.0)
  * rack-ssl (1.3.3)
  * rack-test (0.6.2)
  * rails (3.2.13)
  * railties (3.2.13)
  * rake (10.1.0)
  * rdoc (3.12.2)
  * ref (1.0.4)
  * rspec (2.13.0)
  * rspec-core (2.13.1)
  * rspec-expectations (2.13.0)
  * rspec-mocks (2.13.1)
  * rspec-rails (2.13.2)
  * rvm-capistrano (1.2.7)
  * sass (3.2.8)
  * sass-rails (3.2.6)
  * shoulda (3.3.2)
  * shoulda-context (1.0.1)
  * shoulda-matchers (1.4.1)
  * simplecov (0.7.1)
  * simplecov-html (0.7.1)
  * sprockets (2.2.2)
  * therubyracer (0.11.4)
  * thor (0.18.1)
  * tilt (1.4.1)
  * timecop (0.5.3)
  * treetop (1.4.14)
  * twitter-bootstrap-rails (2.2.6)
  * tzinfo (0.3.37)
  * uglifier (2.0.1)
  * warden (1.2.1)
  * will_paginate (3.0.4)
  * xpath (2.0.0)
```

ruby 2.0.0p0 (2013-02-24 revision 39474) [i686-linux]

Please let me know if you need any more info.

Thanks!

**Comment by calleerlandsson** [comment]
Hey @richhollis, I'm sorry we haven't responded to this issue. Did you resolve the issue yourself or are you still having it?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.

**Comment by richhollis** [comment]
Hey @calebthompson - Wow, I'd forgotten I'd even raised this! I've not seen this problem at all in the past year or two, so very safe to close!

**Comment by calebthompson** [comment]
Cc @calleerlandsson

**Comment by calleerlandsson** [comment]
Thanks @richhollis.
