### ISSUE TITLE
Error with Ruby 1.9.3 and 2.0

### ISSUE THREAD

**Issue by fcoury** [thoughtbot/capybara-webkit#572]
Same error:

```
(...)
g++ -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -o ./webkit_server Version.o EnableLogging.o Authenticate.o SetConfirmAction.o SetPromptAction.o SetPromptText.o ClearPromptText.o JavascriptAlertMessages.o JavascriptConfirmMessages.o JavascriptPromptMessages.o IgnoreSslErrors.o ResizeWindow.o CurrentUrl.o ConsoleMessages.o main.o WebPage.o Server.o Connection.o Command.o SocketCommand.o Visit.o Reset.o Node.o JavascriptInvocation.o Evaluate.o Execute.o FrameFocus.o Response.o NetworkAccessManager.o NetworkCookieJar.o Header.o Render.o body.o Status.o Headers.o UnsupportedContentHandler.o SetCookie.o ClearCookies.o GetCookies.o CommandParser.o CommandFactory.o SetProxy.o NullCommand.o PageLoadingCommand.o SetTimeout.o GetTimeout.o SetSkipImageLoading.o WebPageManager.o WindowFocus.o GetWindowHandles.o GetWindowHandle.o TimeoutCommand.o SetUrlBlacklist.o NoOpReply.o JsonSerializer.o InvocationResult.o ErrorMessage.o Title.o FindCss.o JavascriptCommand.o FindXpath.o NetworkReplyProxy.o moc_Version.o moc_EnableLogging.o moc_Authenticate.o moc_SetConfirmAction.o moc_SetPromptAction.o moc_SetPromptText.o moc_ClearPromptText.o moc_JavascriptAlertMessages.o moc_JavascriptConfirmMessages.o moc_JavascriptPromptMessages.o moc_IgnoreSslErrors.o moc_ResizeWindow.o moc_CurrentUrl.o moc_ConsoleMessages.o moc_WebPage.o moc_Server.o moc_Connection.o moc_Command.o moc_SocketCommand.o moc_Visit.o moc_Reset.o moc_Node.o moc_JavascriptInvocation.o moc_Evaluate.o moc_Execute.o moc_FrameFocus.o moc_Response.o moc_NetworkAccessManager.o moc_NetworkCookieJar.o moc_Header.o moc_Render.o moc_Body.o moc_Status.o moc_Headers.o moc_UnsupportedContentHandler.o moc_SetCookie.o moc_ClearCookies.o moc_GetCookies.o moc_CommandParser.o moc_CommandFactory.o moc_SetProxy.o moc_NullCommand.o moc_PageLoadingCommand.o moc_SetSkipImageLoading.o moc_WebPageManager.o moc_WindowFocus.o moc_GetWindowHandles.o moc_GetWindowHandle.o moc_GetTimeout.o moc_SetTimeout.o moc_TimeoutCommand.o moc_SetUrlBlacklist.o moc_NoOpReply.o moc_JsonSerializer.o moc_ErrorMessage.o moc_Title.o moc_FindCss.o moc_JavascriptCommand.o moc_FindXpath.o moc_NetworkReplyProxy.o qrc_webkit_server.o   -F/usr/local/Cellar/qt/4.8.5/lib -L/usr/local/Cellar/qt/4.8.5/lib -framework QtWebKit -framework QtGui -L/opt/X11/lib -L/usr/local/Cellar/qt/4.8.5/lib -F/usr/local/Cellar/qt/4.8.5/lib -framework QtCore -framework QtNetwork
/Users/fcoury/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - src/webkit_server (Errno::ENOENT)
	from /Users/fcoury/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /Users/fcoury/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1529:in `fu_each_src_dest0'
	from /Users/fcoury/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
	from /Users/fcoury/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/fileutils.rb:395:in `cp'
	from /Users/fcoury/.rvm/gems/ruby-1.9.3-p327/gems/capybara-webkit-1.0.0/lib/capybara_webkit_builder.rb:76:in `build'
	from /Users/fcoury/.rvm/gems/ruby-1.9.3-p327/gems/capybara-webkit-1.0.0/lib/capybara_webkit_builder.rb:88:in `build_all'
	from extconf.rb:2:in `<main>'
```

Here's the complete `gem_make.out`: https://gist.github.com/6737975

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity.

**Comment by fcoury** [comment]
This was a CDPATH issue just like @jferris pointed out.
