### ISSUE TITLE
ArgumentError: invalid number of elements (5 for 1..2)

### ISSUE THREAD

**Issue by eddorre** [thoughtbot/capybara-webkit#601]
qt version: 4.8.5
capybara version: 2.2.0
capybara webkit version: 1.1.0
ruby version: 2.0.0-p247
rails version: 4.0.1

After upgrading Rails from 3.2.15 to 4.0.1, I started receiving errors on a spec when trying to inspect the page.response_headers.

The error is the same as the issue title. The error is occurring in this file:

capybara-webkit-1.1.0/lib/capybara/webkit/browser.rb:74:in `[]'

If I set the driver to Webkit Debug and try to access the response headers, I get the following:

```
Received "Headers"
Started "Headers"
Finished "Headers" with response "Success(X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Ua-Compatible: chrome=1
Content-Security-Policy-Report-Only: default-src https: data: 'unsafe-inline' 'unsafe-eval'; frame-src https://* about: javascript:; img-src data:
Content-Type: text/html; charset=utf-8
Etag: "59df19094135a9fb03c6462eb09facb2"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: e6626902-fb10-4c25-a3b5-2c50fb70a873
X-Runtime: 0.021853
Server: WEBrick/1.3.1 (Ruby/2.0.0/2013-06-27)
Date: Sat, 14 Dec 2013 00:56:36 GMT
Content-Length: 2312
Connection: Keep-Alive)"
Wrote response true "X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Ua-Compatible: chrome=1
Content-Security-Policy-Report-Only: default-src https: data: 'unsafe-inline' 'unsafe-eval'; frame-src https://* about: javascript:; img-src data:
Content-Type: text/html; charset=utf-8
Etag: "59df19094135a9fb03c6462eb09facb2"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: e6626902-fb10-4c25-a3b5-2c50fb70a873
X-Runtime: 0.021853
Server: WEBrick/1.3.1 (Ruby/2.0.0/2013-06-27)
Date: Sat, 14 Dec 2013 00:56:36 GMT
Content-Length: 2312
Connection: Keep-Alive"
ArgumentError: invalid number of elements (5 for 1..2)
from /myproject/vendor/ruby/2.0.0/gems/capybara-webkit-1.1.0/lib/capybara/webkit/browser.rb:74:in `[]'
```

In the spec all that I'm doing is signing in and then inspecting that response_headers:

```ruby
        puts "HEADERS #{page.response_headers.inspect}"
```

**Comment by calleerlandsson** [comment]
@eddorre Can you confirm whether or not you're still having these issues using the latest version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please feel free to re-open it if you're still having these issues.
