### ISSUE TITLE
'Capybara::Webkit::CrashError:' interacting with element in 'within_frame' block

### ISSUE THREAD

**Issue by nvreynolds** [thoughtbot/capybara-webkit#825]
```
  ruby '2.0.0', :patchlevel => '598'
  gem 'rails', '~> 4.1.1'
.
.
.
  gem 'capybara', '~>  2.4.4 '
  gem 'capybara-webkit', '~>  1.6.0'
```

config:

```
Capybara.configure do |c|
  c.ignore_hidden_elements  = true
  c.default_driver          = :webkit
  c.javascript_driver       = :webkit_debug
  c.default_wait_time       = 8
end
```

error:

```
 Failure/Error: within_frame frame_name do
     Capybara::Webkit::CrashError:
       The webkit_server process crashed!

         Connection reset by peer

       This is a bug in capybara-webkit. For help with this crash, please visit:

       https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:215:in `rescue in command'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:205:in `command'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:90:in `frame_focus'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.6.0/lib/capybara/webkit/driver.rb:141:in `ensure in within_frame'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.6.0/lib/capybara/webkit/driver.rb:141:in `within_frame'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-2.4.4/lib/capybara/session.rb:327:in `within_frame'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/acceptance/candidate_spec.rb:28:in `block (2 levels) in <top (required)>'

```

code:

```
source1 = page.html

within_frame frame_name do
    source2 = page.html
    find(:xpath, '//somevalidxpath').click
end
```

I validated source 2 is the frame I am wanting to interact with and source 1 is the original page.

I made sure that this code executes written in Python's selenium webdriver bindings with Chrome Driver

I also was experiencing this error in older versions of capybara-webkit with the error

```
     Failure/Error: within_frame frame_name do
     Errno::EPIPE:
       Broken pipe
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/connection.rb:30:in `write'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/connection.rb:30:in `puts'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/connection.rb:30:in `puts'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/browser.rb:205:in `command'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/browser.rb:89:in `frame_focus'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/driver.rb:130:in `ensure in within_frame'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-webkit-1.5.2/lib/capybara/webkit/driver.rb:130:in `within_frame'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-2.4.4/lib/capybara/session.rb:327:in `within_frame'
     # /Users/nathanreynolds/.rvm/gems/ruby-2.0.0-p598/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/acceptance/candidate_spec.rb:29:in `block (2 levels) in <top (required)>'


```

Debug JS driver didnt give me anything useful. 

Any guidance here would be great!  I didn't find anything anywhere else, besides users going between tests/threads, not within a test.

**Comment by twalpole** [comment]
Closing due to age - We can reopen if this is still happening with current release and away to replicate is provided
