### ISSUE TITLE
The webkit_server process crashed! -- Broken pipe

### ISSUE THREAD

**Issue by boblail** [thoughtbot/capybara-webkit#835]
Hello,

I have my test suite passing on Ubuntu 14.04.2 using Cucumber, Capybara, and Poltergeist. I'm trying to switch from Poltergeist to Capybara Webkit, but I get this output:

```
  @javascript
  Scenario: If comments are not moderated, I see a comment after I post it # features/CMS Features/feeds/comments_on_feeds.feature:21
    Given I am signed in                                                   # features/step_definitions/authentication_steps.rb:27
    And a feed "Sermons"                                                   # features/step_definitions/feed_steps.rb:8
    And a post "Grace, Mercy, and Peace" in the feed                       # features/step_definitions/post_steps.rb:24
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetUnknownUrlMode(block)"
Started "SetUnknownUrlMode(block)"
Finished "SetUnknownUrlMode(block)" with response "Success()"
Wrote response true ""
Received "IgnoreSslErrors()"
Started "IgnoreSslErrors()"
Finished "IgnoreSslErrors()" with response "Success()"
Wrote response true ""
Received "SetSkipImageLoading(true)"
Started "SetSkipImageLoading(true)"
Finished "SetSkipImageLoading(true)" with response "Success()"
Wrote response true ""
Received "SetTimeout(5)"
Started "SetTimeout(5)"
Finished "SetTimeout(5)" with response "Success()"
Wrote response true ""
Received "Visit(http://cucumber.localhost:54163/sermons/2015/9/new-post-3)"
Started "Visit(http://cucumber.localhost:54163/sermons/2015/9/new-post-3)"
Load started
"Visit(http://cucumber.localhost:54163/sermons/2015/9/new-post-3)" started page load
Started request to "http://cucumber.localhost:54163/sermons/2015/9/new-post-3"
Finished "Visit(http://cucumber.localhost:54163/sermons/2015/9/new-post-3)" with response "Success()"
Started request to "http://cucumber.localhost:54163/assets/common.css"
Started request to "http://cucumber.localhost:54163/themes/modern/stylesheets/theme.css"
Started request to "http://cucumber.localhost:54163/assets/common.js"
Started request to "http://cucumber.localhost:54163/themes/modern/javascripts/theme.js"
Received 200 from "http://cucumber.localhost:54163/sermons/2015/9/new-post-3"
Received 200 from "http://cucumber.localhost:54163/assets/common.css"
http://cucumber.localhost:54163/sermons/2015/9/new-post-3|29|Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 144dpi)
Received 200 from "http://cucumber.localhost:54163/themes/modern/stylesheets/theme.css"
Received 200 from "http://cucumber.localhost:54163/assets/common.js"
    When I go to the post                                                  # features/step_definitions/web_steps.rb:30
      end of file reached (EOFError)
      ./features/step_definitions/web_steps.rb:31:in `/^(?:|I )go to (.+)$/'
      features/CMS Features/feeds/comments_on_feeds.feature:25:in `When I go to the post'
    And I fill in "comment_content" with "I can say whatever I want"       # features/step_definitions/web_steps.rb:42
    And I press "Post"                                                     # features/step_definitions/web_steps.rb:34
    Then I should see "I can say whatever I want"                          # features/step_definitions/web_steps.rb:87
      The webkit_server process crashed!

        Broken pipe

      This is a bug in capybara-webkit. For help with this crash, please visit:

      https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes (Capybara::Webkit::CrashError)
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.7.0/lib/capybara/webkit/browser.rb:215:in `rescue in command'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.7.0/lib/capybara/webkit/browser.rb:205:in `command'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.7.0/lib/capybara/webkit/browser.rb:39:in `reset!'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.7.0/lib/capybara/webkit/driver.rb:262:in `reset!'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara/session.rb:103:in `reset!'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara.rb:257:in `block in reset_sessions!'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara.rb:257:in `each'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara.rb:257:in `reset_sessions!'
      /var/lib/jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.4/lib/capybara/cucumber.rb:8:in `After'
```

Here's the output from `page.driver.version`:

> Capybara: 2.4.4
> capybara-webkit: 1.7.0
> Qt: 5.2.1
> WebKit: 537.21
> QtWebKit: 5.1.1

And my config looks like this:

```
Capybara::Webkit.configure do |config|
  config.block_unknown_urls
  config.timeout = 5
  config.ignore_ssl_errors
  config.skip_image_loading
end
```

**Comment by galaydaroman** [comment]
Hi. Was the same for me, just try to install additional packages on your system:
```sh
apt-get install gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
```

Maybe I will need to rebuild capybara-webkit binaries

**Comment by darryn02** [comment]
Seeing the same, pretty frequently, after upgrading to v1.7.1 from 1.6.0 (simultaneously upgraded Capybara to 2.5.0 from 2.4.4).

**Comment by trusche** [comment]
Same on CentOS 6.7. Downgrading to 1.6.0/2.4.4 did not help.

**Comment by twalpole** [comment]
Closing due to age -- if this is still an issue with current releases on Qt5.5+ we can reopen
