### ISSUE TITLE
Capybara::Webkit::CrashError

### ISSUE THREAD

**Issue by modernlegend** [thoughtbot/capybara-webkit#931]
Hi guys, 
We are trying to run integration tests with Capybara-webkit and are getting errors. Could you please help?

We have the following setup on circle:
Caybara-webkit version: 1.8.0
Ruby version: 2.1.8
Driver version info: Capybara: 2.6.0
Qt: 5.2.1
WebKit: 537.21
QtWebKit: 5.1.1

Here are the errors we are getting, which appear to be independent of the code itself, and instead related to the capybara-webkit library:

```
ruby run in 6.803678s, 2.0577 runs/s, 1.9107 assertions/s.

  1) Error:
logging in as a client#test_0004_displays the impressions stats modal:
Capybara::Webkit::CrashError: The webkit_server process crashed!

  Connection reset by peer

This is a bug in capybara-webkit. For help with this crash, please visit:

https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
    test/integration/client_views_stats_overview_page_test.rb:46:in `block (2 levels) in <class:ClientViewsStatsOverviewTest>'
    test/test_helper.rb:68:in `call'
    test/test_helper.rb:68:in `around'

  2) Error:
logging in as a client#test_0005_displays the return in value modal:
Capybara::Webkit::CrashError: The webkit_server process crashed!

  Connection reset by peer

This is a bug in capybara-webkit. For help with this crash, please visit:

https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
    test/integration/client_views_stats_overview_page_test.rb:60:in `block (2 levels) in <class:ClientViewsStatsOverviewTest>'
    test/test_helper.rb:68:in `call'
    test/test_helper.rb:68:in `around'


  3) Error:
logging in as a client#test_0002_displays data for the categories:
EOFError: end of file reached
    test/integration/client_views_stats_overview_page_test.rb:11:in `block (2 levels) in <class:ClientViewsStatsOverviewTest>'
    test/test_helper.rb:68:in `call'
    test/test_helper.rb:68:in `around'


  4) Error:
logging in as a client#test_0003_displays the engagements stats modal:
Capybara::Webkit::CrashError: The webkit_server process crashed!

  Broken pipe

This is a bug in capybara-webkit. For help with this crash, please visit:

https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
    test/helpers/sessions.rb:3:in `sign_in_with_client'
    test/integration/client_views_stats_overview_page_test.rb:9:in `block (2 levels) in <class:ClientViewsStatsOverviewTest>'
    test/test_helper.rb:68:in `call'
    test/test_helper.rb:68:in `around'


  5) Error:
logging in as a client#test_0001_displays the correct categories for the data:
EOFError: end of file reached
    test/integration/client_views_stats_overview_page_test.rb:11:in `block (2 levels) in <class:ClientViewsStatsOverviewTest>'
    test/test_helper.rb:68:in `call'
    test/test_helper.rb:68:in `around'


  6) Error:
forgetting your client password#test_0001_allows you to request to reset your password:
Capybara::Webkit::CrashError: The webkit_server process crashed!

  Broken pipe

This is a bug in capybara-webkit. For help with this crash, please visit:

https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
    test/integration/client_auth_test.rb:35:in `block (2 levels) in <class:ClientAuthTest>'
    test/test_helper.rb:68:in `call'
    test/test_helper.rb:68:in `around'

14 runs, 13 assertions, 0 failures, 6 errors, 0 skips

generating ci files

RAILS_ENV=minitest bundle exec rake test TESTOPTS="--ci-dir=$CIRCLE_TEST_REPORTS" returned exit code 1
```

**Comment by mhoran** [comment]
Hey @modernlegend. Qt 5.1 is pretty old at this point (over 3 years), so I'd recommend trying to get Qt 5.5 if possible. If not, it's possible that we can resurrect a branch that will expose stack traces and possibly identify the source of the crash, but it's likely that will point to a Qt issue.

**Comment by modernlegend** [comment]
Thanks @mhoran :)
